"""password

Revision ID: 001db67f5b7d
Revises: 15f49afd4442
Create Date: 2023-12-14 04:12:59.663395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001db67f5b7d'
down_revision = '15f49afd4442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
