"""changes

Revision ID: 2ebc1862b173
Revises: 
Create Date: 2023-12-07 23:20:09.017920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebc1862b173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_balance', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cash_balance_document_number', ['document_number'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_expenses_document_number', ['document_number'])

    with op.batch_alter_table('payables', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_payables_document_number', ['document_number'])

    with op.batch_alter_table('receivables', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_receivables_document_number', ['document_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('payables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('cash_balance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
